apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: bmocp.qeclusters.arm.eng.rdu2.redhat.com
            - name: NFS_PATH
              value: /srv/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: bmocp.qeclusters.arm.eng.rdu2.redhat.com
            path: /srv/nfs
